os: windows
language: shell  # MEANINGLESS!
before_script:
  - env
  - where wsl
  - where wslconfig
script:
  - powershell -ExecutionPolicy RemoteSigned -File install.ps1 -Distro Ubuntu-18.04
  - powershell -Command "wslconfig /l"
  - wsl cat /etc/os-release
