os: windows
language: shell  # MEANINGLESS!
script:
  - where wsl
  - where wslconfig
  - wslconfig /l
  - dir
  - powershell -Command Get-ExecutionPolicy
  - powershell -ExecutionPolicy RemoteSigned -File install.ps1 -Distro Ubuntu-18.04
  - dir
  - wslconfig /l
